Repository composer-dev/composer, pull requests merged in 2023-02, with the labels that each got.

#9 Rename EditorGame to Composer & composer.Tests to composer.Editor.Tests
  composer.Desktop/ComposerDesktop.cs
  composer.Editor.Tests/EditorTestBrowser.cs
  composer.Editor.Tests/Program.cs
  composer.Editor.Tests/UnitTest1.cs
  composer.Editor.Tests/Visual/TestSceneComposer.cs
  composer.Editor.Tests/composer.Editor.Tests.csproj
  composer.Editor/Composer.cs
  composer.sln
Labels: type:code-quality

#8 Create main menu button
  composer.Editor.Tests/Visual/Menu/TestSceneMenuButton.cs
  composer.Editor/Composer.cs
  composer.Editor/Screens/Menu/MainMenu.cs
  composer.Editor/Screens/Menu/MenuButton.cs
Labels: type:design

#10 Implement beatmap set card
  composer.Desktop/ComposerDesktop.cs
  composer.Editor.Tests/Resources/TestResources.cs
  composer.Editor.Tests/Visual/Select/TestSceneBeatmapSetCard.cs
  composer.Editor/Composer.cs
  composer.Editor/Screens/Menu/MainMenu.cs
  composer.Editor/Screens/Select/BeatmapSelect.cs
  composer.Editor/Screens/Select/Carousel/BeatmapSetCard.cs
  composer.Editor/Screens/Select/Carousel/BeatmapSetPanelBackground.cs
  composer.Editor/Screens/Select/Carousel/BeatmapSetPanelContent.cs
  composer.Editor/composer.Editor.csproj
  composer.sln.DotSettings
Labels: type:ui

#11 Create beatmap card drawable
  composer.Editor.Tests/Visual/Select/TestSceneBeatmapCard.cs
  composer.Editor/Graphics/ComposerColour.cs
  composer.Editor/Screens/Select/Carousel/BeatmapCard.cs
Labels: type:ui
